### ISSUE TITLE
Review documentation

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/docs#4]

**Comment by ybvau** [comment]
https://ironhacks.github.io/docs/2-Developer-Documentation/install/
line 11: Unless we are to clone the platform, in which why is it not git clone git@github.com:rcodi/the-ironhacks-platform instead ? 
line 15: Under setup, would we want to cd ironhacks-app ?

https://ironhacks.github.io/docs/2-Developer-Documentation/services/
line 32: The end of "Preparation" is, "We will get into the details below". Is this referring to Section 3, Cloud API, or is there more to get into?

**Comment by ybvau** [comment]
https://ironhacks.github.io/docs/3-Cloud-Api/overview/
lines 15-21: It seems there are headers for the sections "Repository" and "References", but they contain no content. I am wondering if these might need to be written?

https://ironhacks.github.io/docs/3-Cloud-Api/setup/
line 38: It seems there is a missing reference URL related to the Firebase project and/or environment variables.
